In [2]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

In [154]:
data=pd.read_csv('TelecomChurnData.csv')

In [155]:
data

State  Account Length  Area Code Phone Number International Plan  \
0       KS             128        415     382-4657                 no   
1       OH             107        415     371-7191                 no   
2       NJ             137        415     358-1921                 no   
3       OH              84        408     375-9999                yes   
4       OK              75        415     330-6626                yes   
5       AL             118        510     391-8027                yes   
6       MA             121        510     355-9993                 no   
7       MO             147        415     329-9001                yes   
8       LA             117        408     335-4719                 no   
9       WV             141        415     330-8173                yes   
10      IN              65        415     329-6603                 no   
11      RI              74        415     344-9403                 no   
12      IA             168        408     363-1107                 no   
13      MT              95        510     394-8006                 no   
14      IA              62        415     366-9238                 no   
15      NY             161        415     351-7269                 no   
16      ID              85        408     350-8884                 no   
17      VT              93        510     386-2923                 no   
18      VA              76        510     356-2992                 no   
19      TX              73        415     373-2782                 no   
20      FL             147        415     396-5800                 no   
21      CO              77        408     393-7984                 no   
22      AZ             130        415     358-1958                 no   
23      SC             111        415     350-2565                 no   
24      VA             132        510     343-4696                 no   
25      NE             174        415     331-3698                 no   
26      WY              57        408     357-3817                 no   
27      MT              54        408     418-6412                 no   
28      MO              20        415     353-2630                 no   
29      HI              49        510     410-7789                 no   
...    ...             ...        ...          ...                ...   
4970    MD             133        415     363-2715                 no   
4971    HI             128        510     409-8074                 no   
4972    FL              81        408     357-1624                 no   
4973    ND              81        415     342-2543                 no   
4974    LA              96        408     347-4427                 no   
4975    AR              93        415     411-9580                 no   
4976    KY             145        408     338-1170                 no   
4977    HI              53        510     356-5217                yes   
4978    KS             108        408     389-4921                 no   
4979    TX              52        415     330-3162                 no   
4980    WA              73        408     408-8236                 no   
4981    NC              61        510     408-3742                 no   
4982    TX              86        408     360-8716                 no   
4983    LA             137        408     400-1731                 no   
4984    TN              74        510     341-2423                 no   
4985    NC             118        510     344-6099                 no   
4986    OH             125        415     364-2584                 no   
4987    AR             127        415     397-4141                 no   
4988    WA              80        510     397-4475                 no   
4989    MN             150        408     407-6315                 no   
4990    ND             140        510     364-8203                 no   
4991    AZ              97        510     410-3888                 no   
4992    MT              83        415     355-3630             

In [156]:
data


State  Account Length  Area Code Phone Number International Plan  \
0       KS             128        415     382-4657                 no   
1       OH             107        415     371-7191                 no   
2       NJ             137        415     358-1921                 no   
3       OH              84        408     375-9999                yes   
4       OK              75        415     330-6626                yes   
5       AL             118        510     391-8027                yes   
6       MA             121        510     355-9993                 no   
7       MO             147        415     329-9001                yes   
8       LA             117        408     335-4719                 no   
9       WV             141        415     330-8173                yes   
10      IN              65        415     329-6603                 no   
11      RI              74        415     344-9403                 no   
12      IA             168        408     363-1107                 no   
13      MT              95        510     394-8006                 no   
14      IA              62        415     366-9238                 no   
15      NY             161        415     351-7269                 no   
16      ID              85        408     350-8884                 no   
17      VT              93        510     386-2923                 no   
18      VA              76        510     356-2992                 no   
19      TX              73        415     373-2782                 no   
20      FL             147        415     396-5800                 no   
21      CO              77        408     393-7984                 no   
22      AZ             130        415     358-1958                 no   
23      SC             111        415     350-2565                 no   
24      VA             132        510     343-4696                 no   
25      NE             174        415     331-3698                 no   
26      WY              57        408     357-3817                 no   
27      MT              54        408     418-6412                 no   
28      MO              20        415     353-2630                 no   
29      HI              49        510     410-7789                 no   
...    ...             ...        ...          ...                ...   
4970    MD             133        415     363-2715                 no   
4971    HI             128        510     409-8074                 no   
4972    FL              81        408     357-1624                 no   
4973    ND              81        415     342-2543                 no   
4974    LA              96        408     347-4427                 no   
4975    AR              93        415     411-9580                 no   
4976    KY             145        408     338-1170                 no   
4977    HI              53        510     356-5217                yes   
4978    KS             108        408     389-4921                 no   
4979    TX              52        415     330-3162                 no   
4980    WA              73        408     408-8236                 no   
4981    NC              61        510     408-3742                 no   
4982    TX              86        408     360-8716                 no   
4983    LA             137        408     400-1731                 no   
4984    TN              74        510     341-2423                 no   
4985    NC             118        510     344-6099                 no   
4986    OH             125        415     364-2584                 no   
4987    AR             127        415     397-4141                 no   
4988    WA              80        510     397-4475                 no   
4989    MN             150        408     407-6315                 no   
4990    ND             140        510     364-8203                 no   
4991    AZ              97        510     410-3888                 no   
4992    MT              83        415     355-3630             

In [157]:
data.drop(['Phone Number'],axis=1,inplace=True)

In [344]:
data

State  Account Length  Area Code International Plan Voice mail Plan  \
0       KS             128        415                 no             yes   
1       OH             107        415                 no             yes   
2       NJ             137        415                 no              no   
3       OH              84        408                yes              no   
4       OK              75        415                yes              no   
5       AL             118        510                yes              no   
6       MA             121        510                 no             yes   
7       MO             147        415                yes              no   
8       LA             117        408                 no              no   
9       WV             141        415                yes             yes   
10      IN              65        415                 no              no   
11      RI              74        415                 no              no   
12      IA             168        408                 no              no   
13      MT              95        510                 no              no   
14      IA              62        415                 no              no   
15      NY             161        415                 no              no   
16      ID              85        408                 no             yes   
17      VT              93        510                 no              no   
18      VA              76        510                 no             yes   
19      TX              73        415                 no              no   
20      FL             147        415                 no              no   
21      CO              77        408                 no              no   
22      AZ             130        415                 no              no   
23      SC             111        415                 no              no   
24      VA             132        510                 no              no   
25      NE             174        415                 no              no   
26      WY              57        408                 no             yes   
27      MT              54        408                 no              no   
28      MO              20        415                 no              no   
29      HI              49        510                 no              no   
...    ...             ...        ...                ...             ...   
4970    MD             133        415                 no              no   
4971    HI             128        510                 no             yes   
4972    FL              81        408                 no              no   
4973    ND              81        415                 no              no   
4974    LA              96        408                 no              no   
4975    AR              93        415                 no              no   
4976    KY             145        408                 no              no   
4977    HI              53        510                yes              no   
4978    KS             108        408                 no              no   
4979    TX              52        415                 no              no   
4980    WA              73        408                 no              no   
4981    NC              61        510                 no              no   
4982    TX              86        408                 no              no   
4983    LA             137        408                 no              no   
4984    TN              74        510                 no              no   
4985    NC             118        510                 no             yes   
4986    OH             125        415                 no              no   
4987    AR             127        415                 no             yes   
4988    WA              80        510                 no              no   
4989    MN             150        408                 no              no   
4990    ND             140        510                

In [345]:
data['State'].unique().size

51

In [362]:
X=data.iloc[:,0:19].values
y=data.iloc[:,-1].values

In [363]:
type(X)

numpy.ndarray

In [364]:
from sklearn.model_selection import train_test_split

In [365]:
from sklearn.preprocessing import LabelEncoder,OneHotEncoder

In [366]:
labelencoder_X_0=LabelEncoder()

In [367]:
X[:,0]=labelencoder_X_0.fit_transform(X[:,0])

In [368]:
labelencoder_X_3=LabelEncoder()

In [369]:
X[:,3]=labelencoder_X_3.fit_transform(X[:,3])

In [370]:
labelencoder_X_4=LabelEncoder()

In [371]:
X[:,4]=labelencoder_X_4.fit_transform(X[:,4])

In [372]:

labelencoder_y_1=LabelEncoder()

In [373]:
y=labelencoder_y_1.fit_transform(y)

In [374]:
y[0]

0

In [375]:
X[0].size

19

In [376]:
X[0]

array([16, 128, 415, 0, 1, 25, 265.1, 110, 45.07, 197.4, 99, 16.78, 244.7,
       91, 11.01, 10.0, 3, 2.7, 1], dtype=object)

In [377]:
onehotencoder=OneHotEncoder(categorical_features=[1])

In [378]:
X=onehotencoder.fit_transform(X).toarray()

In [379]:
X2=X

In [380]:
XX=X.astype(int,copy=True)

In [381]:

X=XX

In [382]:
X[0].size

236

In [383]:
X[0]


array([  0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
         0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
         0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
         0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
         0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
         0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
         0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
         0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
         0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
         0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   1,   0,   0,
         0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
         0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
         0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
         0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   

In [384]:
X=X[:,166:]

In [385]:
X[0].size

70

In [386]:
X_train,X_test,y_train,y_test = train_test_split(X,y,test_size=0.2,random_state=0)

In [387]:
X_train

array([[0, 0, 0, ..., 4, 2, 1],
       [0, 0, 0, ..., 0, 0, 1],
       [0, 0, 0, ..., 4, 2, 1],
       ...,
       [0, 0, 0, ..., 2, 3, 1],
       [0, 0, 0, ..., 3, 2, 3],
       [0, 0, 0, ..., 2, 4, 5]])

In [388]:
from sklearn.preprocessing import StandardScaler

In [389]:
sc=StandardScaler()

In [390]:
X_train=sc.fit_transform(X_train)

C:\Users\Hidayat1\AppData\Local\Continuum\anaconda3\lib\site-packages\sklearn\utils\validation.py:475: DataConversionWarning: Data with input dtype int32 was converted to float64 by StandardScaler.
  warnings.warn(msg, DataConversionWarning)


In [391]:
X_test=sc.transform(X_test)

C:\Users\Hidayat1\AppData\Local\Continuum\anaconda3\lib\site-packages\sklearn\utils\validation.py:475: DataConversionWarning: Data with input dtype int32 was converted to float64 by StandardScaler.
  warnings.warn(msg, DataConversionWarning)


In [392]:
X_test

array([[-0.0525127 , -0.03537746, -0.0548546 , ..., -0.17391723,
        -0.37399981, -0.44155462],
       [-0.0525127 , -0.03537746, -0.0548546 , ..., -0.57979175,
        -1.63751269, -1.20056556],
       [-0.0525127 , -0.03537746, -0.0548546 , ...,  0.23195729,
         0.88951306, -0.44155462],
       ...,
       [-0.0525127 , -0.03537746, -0.0548546 , ..., -0.98566626,
         0.88951306,  0.31745633],
       [-0.0525127 , -0.03537746, -0.0548546 , ..., -0.57979175,
         0.88951306,  0.31745633],
       [-0.0525127 , -0.03537746, -0.0548546 , ...,  0.6378318 ,
        -0.37399981,  1.07646727]])

In [393]:
import keras

In [394]:
from keras.layers import Dense

In [395]:
from keras.models import Sequential

In [396]:
model=Sequential()

In [397]:
model.add((Dense(output_dim = 20,init = 'uniform',activation='relu',input_dim=70)))

C:\Users\Hidayat1\AppData\Local\Continuum\anaconda3\lib\site-packages\ipykernel_launcher.py:1: UserWarning: Update your `Dense` call to the Keras 2 API: `Dense(activation="relu", input_dim=70, units=35, kernel_initializer="uniform")`
  """Entry point for launching an IPython kernel.


In [398]:
model.add(Dense(output_dim = 20 ,init = 'uniform',activation='relu'))

C:\Users\Hidayat1\AppData\Local\Continuum\anaconda3\lib\site-packages\ipykernel_launcher.py:1: UserWarning: Update your `Dense` call to the Keras 2 API: `Dense(activation="relu", units=35, kernel_initializer="uniform")`
  """Entry point for launching an IPython kernel.


In [406]:
model.add(Dense(output_dim = 20 ,init = 'uniform',activation='relu'))

C:\Users\Hidayat1\AppData\Local\Continuum\anaconda3\lib\site-packages\ipykernel_launcher.py:1: UserWarning: Update your `Dense` call to the Keras 2 API: `Dense(activation="relu", units=20, kernel_initializer="uniform")`
  """Entry point for launching an IPython kernel.


In [408]:
model.add(Dense(output_dim = 10 ,init = 'uniform',activation='relu'))

C:\Users\Hidayat1\AppData\Local\Continuum\anaconda3\lib\site-packages\ipykernel_launcher.py:1: UserWarning: Update your `Dense` call to the Keras 2 API: `Dense(activation="relu", units=10, kernel_initializer="uniform")`
  """Entry point for launching an IPython kernel.


In [409]:
model.add(Dense(output_dim = 1,init = 'uniform',activation='sigmoid'))

C:\Users\Hidayat1\AppData\Local\Continuum\anaconda3\lib\site-packages\ipykernel_launcher.py:1: UserWarning: Update your `Dense` call to the Keras 2 API: `Dense(activation="sigmoid", units=1, kernel_initializer="uniform")`
  """Entry point for launching an IPython kernel.


In [410]:
model.compile(optimizer='adam',loss='binary_crossentropy',metrics=['accuracy'])

In [416]:
model.fit(X_train,y_train,batch_size=10,epochs=100)

Epoch 1/100
4000/4000 [==============================] - 1s 175us/step - loss: 0.1820 - acc: 0.9392
Epoch 2/100
4000/4000 [==============================] - 1s 176us/step - loss: 0.1777 - acc: 0.9397
Epoch 3/100
4000/4000 [==============================] - 1s 176us/step - loss: 0.1697 - acc: 0.9457
Epoch 4/100
4000/4000 [==============================] - 1s 172us/step - loss: 0.1673 - acc: 0.9465
Epoch 5/100
4000/4000 [==============================] - 1s 178us/step - loss: 0.1650 - acc: 0.9472
Epoch 6/100
4000/4000 [==============================] - 1s 184us/step - loss: 0.1636 - acc: 0.9480
Epoch 7/100
4000/4000 [==============================] - 1s 177us/step - loss: 0.1574 - acc: 0.9542
Epoch 8/100
4000/4000 [==============================] - 1s 189us/step - loss: 0.1539 - acc: 0.9527
Epoch 9/100
4000/4000 [==============================] - 1s 193us/step - loss: 0.1534 - acc: 0.9530
Epoch 10/100
4000/4000 [==============================] - 1s 206us/step - loss: 0.1475 - acc: 0.9567

4000/4000 [==============================] - 1s 168us/step - loss: 0.1032 - acc: 0.9775
Epoch 83/100
4000/4000 [==============================] - 1s 166us/step - loss: 0.1044 - acc: 0.9770
Epoch 84/100
4000/4000 [==============================] - 1s 167us/step - loss: 0.1000 - acc: 0.9785
Epoch 85/100
4000/4000 [==============================] - 1s 161us/step - loss: 0.0982 - acc: 0.9792
Epoch 86/100
4000/4000 [==============================] - 1s 172us/step - loss: 0.0957 - acc: 0.9800
Epoch 87/100
4000/4000 [==============================] - 1s 167us/step - loss: 0.0939 - acc: 0.9812
Epoch 88/100
4000/4000 [==============================] - 1s 167us/step - loss: 0.1052 - acc: 0.9762
Epoch 89/100
4000/4000 [==============================] - 1s 167us/step - loss: 0.1004 - acc: 0.9787
Epoch 90/100
4000/4000 [==============================] - 1s 167us/step - loss: 0.0999 - acc: 0.9785
Epoch 91/100
4000/4000 [==============================] - 1s 166us/step - loss: 0.1027 - acc: 0.9772
Epo

In [417]:
type(X_train)

numpy.ndarray

In [468]:
predict=model.predict(X_test)

In [502]:
pred=(predict>0.5)

In [503]:
pred

array([[False],
       [False],
       [False],
       [ True],
       [False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [ True],
       [False],
       [False],
       [False],
       [ True],
       [False],
       [False],
       [ True],
       [False],
       [False],
       [False],
       [ True],
       [False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [ True],
       [False],
       [False],
       [ True],
       [False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [ True],
       [

In [504]:
from sklearn.metrics import confusion_matrix,classification_report

In [505]:
print(classification_report(y_test,pred))

             precision    recall  f1-score   support

          0       0.96      0.98      0.97       874
          1       0.82      0.73      0.77       126

avg / total       0.94      0.95      0.94      1000



In [506]:
print(confusion_matrix(y_test,pred))

[[854  20]
 [ 34  92]]


In [509]:
acuracy=(946/1000)

In [510]:
acuracy

0.946