In [8]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

In [9]:
%matplotlib inline

In [10]:
hr=pd.read_csv('trainHR1.csv')

In [11]:
import re

In [12]:
Region=[]
for i in hr['region']:

    for s in re.findall('\d+',i):
        Region.append(s)
       
    
    
    


In [13]:
hr['region']=Region

In [14]:
def imput_edu(cols):
    education=cols[0]
    department = cols[1]
    if pd.isnull(education):
        if department=="R&D" or "Sales & Marketing" or "Operations" or "HR":
            return "Master's&above"
        elif department=="Analytics" or "Technology":
            return "Bachelor's"
        else:
        
            return "secondary"
        
    else:
        return education
        
    

In [15]:
hr['education']=hr[['education','department']].apply(imput_edu,axis=1)

In [16]:
def imput_rat(cols):
    previous_year_rating=cols[0]
    department = cols[1]
    if pd.isnull(previous_year_rating):
        if department=="R&D" or "Sales & Marketing" or "Operations" or "HR":
            return 5
        elif department=="Analytics" or "Technology":
            return 4
        else:
        
            return 3
        
    else:
        return previous_year_rating
        

In [17]:
hr['previous_year_rating']=hr[['previous_year_rating','department']].apply(imput_rat,axis=1)

In [18]:
hr.drop(['employee_id'],axis=1,inplace=True)

In [19]:
hr['department']=hr['department'].str.replace(" & ","")

In [20]:
hr['department']=[i.lower() for i in hr['department']]

In [21]:
hr['education']=hr['education'].str.replace(" & ","")

In [23]:
hr['education']=[str(i) for i in hr['education']]
hr['education']=[i.lower() for i in hr['education']]

In [24]:
X=hr.iloc[:,0:12].values
y=hr.iloc[:,-1].values

In [25]:
from sklearn.preprocessing import LabelEncoder,OneHotEncoder

In [26]:
labelencoder_d=LabelEncoder()

In [27]:
X[:,0]=labelencoder_d.fit_transform(X[:,0])

In [28]:
labelencoder_e=LabelEncoder()

In [29]:
X[:,2]=labelencoder_e.fit_transform(X[:,2])

In [30]:
labelencoder_g=LabelEncoder()

In [31]:
X[:,3]=labelencoder_g.fit_transform(X[:,3])

In [32]:
labelencoder_c=LabelEncoder()

In [33]:
X[:,4]=labelencoder_c.fit_transform(X[:,4])

In [34]:
X

array([[7, '7', 3, ..., 1, 0, 49],
       [4, '22', 0, ..., 0, 0, 60],
       [7, '19', 0, ..., 0, 0, 50],
       ...,
       [0, '1', 0, ..., 1, 0, 79],
       [7, '9', 2, ..., 0, 0, 45],
       [2, '22', 0, ..., 0, 0, 49]], dtype=object)

In [35]:
from sklearn.model_selection import train_test_split

In [36]:
 X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=0)

In [37]:
from sklearn.svm import SVC

In [38]:
from sklearn.linear_model import ridge

In [39]:
from sklearn.model_selection import GridSearchCV

In [40]:
para_grid={'C':[0.1,1,10,100,1000],'gamma':[1,0.1,0.001,0.0001]}

In [41]:
grid=GridSearchCV(SVC(),para_grid,verbose=3)

In [42]:
grid.fit(X_train,y_train)

C:\Users\admin\Anaconda3\lib\site-packages\sklearn\model_selection\_split.py:2053: FutureWarning: You should specify a value for 'cv' instead of relying on the default value. The default value will change from 3 to 5 in version 0.22.
  warnings.warn(CV_WARNING, FutureWarning)
[Parallel(n_jobs=1)]: Using backend SequentialBackend with 1 concurrent workers.


Fitting 3 folds for each of 20 candidates, totalling 60 fits
[CV] C=0.1, gamma=1 ..................................................
[CV] ......... C=0.1, gamma=1, score=0.9145457033388068, total= 2.9min
[CV] C=0.1, gamma=1 ..................................................


[Parallel(n_jobs=1)]: Done   1 out of   1 | elapsed:  3.6min remaining:    0.0s


[CV] ......... C=0.1, gamma=1, score=0.9145398563120082, total= 2.8min
[CV] C=0.1, gamma=1 ..................................................


[Parallel(n_jobs=1)]: Done   2 out of   2 | elapsed:  7.3min remaining:    0.0s


[CV] ......... C=0.1, gamma=1, score=0.9145398563120082, total= 2.8min
[CV] C=0.1, gamma=0.1 ................................................
[CV] ....... C=0.1, gamma=0.1, score=0.9145457033388068, total= 2.1min
[CV] C=0.1, gamma=0.1 ................................................
[CV] ....... C=0.1, gamma=0.1, score=0.9145398563120082, total= 2.1min
[CV] C=0.1, gamma=0.1 ................................................
[CV] ....... C=0.1, gamma=0.1, score=0.9145398563120082, total= 2.0min
[CV] C=0.1, gamma=0.001 ..............................................
[CV] ..... C=0.1, gamma=0.001, score=0.9145457033388068, total=  18.8s
[CV] C=0.1, gamma=0.001 ..............................................
[CV] ..... C=0.1, gamma=0.001, score=0.9145398563120082, total=  19.2s
[CV] C=0.1, gamma=0.001 ..............................................
[CV] ..... C=0.1, gamma=0.001, score=0.9145398563120082, total=  18.7s
[CV] C=0.1, gamma=0.0001 .............................................
[CV] .

[Parallel(n_jobs=1)]: Done  60 out of  60 | elapsed: 147.1min finished


GridSearchCV(cv='warn', error_score='raise-deprecating',
       estimator=SVC(C=1.0, cache_size=200, class_weight=None, coef0=0.0,
  decision_function_shape='ovr', degree=3, gamma='auto_deprecated',
  kernel='rbf', max_iter=-1, probability=False, random_state=None,
  shrinking=True, tol=0.001, verbose=False),
       fit_params=None, iid='warn', n_jobs=None,
       param_grid={'C': [0.1, 1, 10, 100, 1000], 'gamma': [1, 0.1, 0.001, 0.0001]},
       pre_dispatch='2*n_jobs', refit=True, return_train_score='warn',
       scoring=None, verbose=3)

In [44]:
predict=grid.predict(X_test)

In [45]:
predict

array([0, 0, 0, ..., 0, 0, 0], dtype=int64)

In [46]:
from sklearn.metrics import classification_report,confusion_matrix

In [47]:
print(classification_report(predict,y_test))

              precision    recall  f1-score   support

           0       1.00      0.93      0.96     10808
           1       0.15      0.91      0.26       154

   micro avg       0.93      0.93      0.93     10962
   macro avg       0.58      0.92      0.61     10962
weighted avg       0.99      0.93      0.95     10962



In [49]:
print(confusion_matrix(predict,y_test))

[[10027   781]
 [   14   140]]


In [50]:
from sklearn.metrics import f1_score

In [54]:
print(f1_score(predict,y_test,average='micro'))

0.9274767378215654


In [55]:
test=pd.read_csv('test_2umaH9m.csv')

In [56]:
test.isnull().any()

employee_id             False
department              False
region                  False
education                True
gender                  False
recruitment_channel     False
no_of_trainings         False
age                     False
previous_year_rating     True
length_of_service       False
KPIs_met >80%           False
awards_won?             False
avg_training_score      False
dtype: bool

In [57]:
test['education']=test[['education','department']].apply(imput_edu,axis=1)

In [58]:
test['previous_year_rating']=test[['previous_year_rating','department']].apply(imput_rat,axis=1)

In [59]:
test.isnull().any()

employee_id             False
department              False
region                  False
education               False
gender                  False
recruitment_channel     False
no_of_trainings         False
age                     False
previous_year_rating    False
length_of_service       False
KPIs_met >80%           False
awards_won?             False
avg_training_score      False
dtype: bool

In [60]:
region=[]
for i in test['region']:

    for s in re.findall('\d+',i):
        region.append(s)
       
    

In [61]:
test['region']=region

In [66]:
test.head()

employee_id         department region   education gender  \
0         8724         Technology     26  Bachelor's      m   
1        74430                 HR      4  Bachelor's      f   
2        72255  Sales & Marketing     13  Bachelor's      m   
3        38562        Procurement      2  Bachelor's      f   
4        64486            Finance     29  Bachelor's      m   

  recruitment_channel  no_of_trainings  age  previous_year_rating  \
0            sourcing                1   24                   5.0   
1               other                1   31                   3.0   
2               other                1   31                   1.0   
3               other                3   31                   2.0   
4            sourcing                1   30                   4.0   

   length_of_service  KPIs_met >80%  awards_won?  avg_training_score  
0                  1              1            0                  77  
1                  5              0            0                  51  
2                  4              0            0                  47  
3                  9              0            0                  65  
4                  7              0            0                  61

In [63]:
ts=test.iloc[:,1:13].values

In [64]:
labelencoder_ts=LabelEncoder()

In [65]:
ts[:,0]=labelencoder_ts.fit_transform(ts[:,0])

In [67]:
labelencoder_ts_d=LabelEncoder()

In [68]:
ts[:,2]=labelencoder_ts_d.fit_transform(ts[:,2])

In [69]:
labelencoder_ts_g=LabelEncoder()

In [70]:
ts[:,3]=labelencoder_ts_g.fit_transform(ts[:,3])

In [71]:
labelencoder_ts_re=LabelEncoder()

In [72]:
ts[:,4]=labelencoder_ts_re.fit_transform(ts[:,4])

In [73]:
ts[0]

array([8, '26', 0, 1, 2, 1, 24, 5.0, 1, 1, 0, 77], dtype=object)

In [74]:
test_predict=grid.predict(ts)

In [75]:
test_predict

array([0, 0, 0, ..., 0, 0, 0], dtype=int64)

In [77]:

submission = pd.DataFrame({'employee_id': test['employee_id'],
                           'is_promoted':test_predict
                           })


In [78]:
submission

employee_id  is_promoted
0             8724            0
1            74430            0
2            72255            0
3            38562            0
4            64486            0
5            46232            0
6            54542            0
7            67269            0
8            66174            0
9            76303            0
10           60245            0
11           42639            0
12           30963            0
13           54055            0
14           42996            0
15           12737            0
16           27561            0
17           26622            0
18           31582            0
19           29793            0
20           72735            0
21            5677            0
22           60889            0
23           51498            0
24            8566            0
25           53151            0
26           16203            0
27           61083            0
28           74849            0
29           13259            0
...            ...          ...
23460        72190            0
23461        27155            0
23462        15959            0
23463        72900            0
23464        57683            0
23465        55174            0
23466        51115            0
23467        50134            0
23468        59775            0
23469        14408            0
23470         4351            0
23471        59625            0
23472        29379            0
23473        67979            0
23474        61451            0
23475        73871            0
23476        52090            0
23477        18488            0
23478        59673            0
23479        39410            0
23480        11837            0
23481        78278            0
23482        27284            0
23483        49291            0
23484        47537            0
23485        53478            0
23486        25600            0
23487        45409            0
23488         1186            0
23489         5973            0

[23490 rows x 2 columns]

In [80]:
submission.to_csv("final_sub_grid.csv",index=False)